# Generated by Django 6.1 on 2026-08-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxa.taxon')),
            ],
        ),
    ]
