# Generated by Django 6.1 on 2026-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='common_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='taxon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='wikipedia_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(choices=[('domain', 'Domain'), ('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], max_length=20),
        ),
    ]
