# Generated by Django 6.1 on 2026-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_taxon_common_name_taxon_description_taxon_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='rank',
            field=models.CharField(choices=[('kingdom', 'Kingdom'), ('phylum', 'Phylum'), ('class', 'Class'), ('order', 'Order'), ('family', 'Family'), ('genus', 'Genus'), ('species', 'Species')], max_length=20),
        ),
    ]
